- name: Chocolatey install and git with paths added
  hosts: all
  tasks:
    - name: Install chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
        force: true
      register: choco_install
    - name: Install git
      win_chocolatey:
        name: git
        state: present
      register: git_install
    - name: Copy path helper to server
      win_copy:
        src: roles/iis/helpers/add_to_path.ps1
        dest: C:\add_to_path.ps1
    - name: Add git to the path
      win_shell: C:\add_to_path.ps1 "C:\Program Files\Git\cmd"
    - name: Cleanup path helper script
      win_file:
        path: C:\add_to_path.ps1
        state: absent
    - name: Sanity check for git in path
      win_command: git --version