- name: test win path
  hosts: all
  tasks:
    # - name: win_path module
      # win_path:
        # elements: '%SystemRoot%\Program Files\Git\cmd'
        # state: present
    - name: attempt to update path variable
      win_command: 'C:\Program Files\Git\cmd\git.exe'