- name: test win path
  hosts: all
  tasks:
    # - name: win_path module
      # win_path:
        # elements: '%SystemRoot%\Program Files\Git\cmd'
        # state: present
    - name: Check if path already has contains git
      win_shell: 'echo %path% | find /C /I "C:\Program Files\Git\cmd"'
      register: result
    - name: Add git to path if needed
      win_shell: $current_path=[Environment]::GetEnvironmentVariable("PATH","Machine"); [Environment]::SetEnvironmentVariable("PATH","$current_path;C:\Program Files\Git\cmd","Machine")
      when: result == 0