---
# Install the main IIS sweet
- name: Install IIS
  win_feature:
    name: "Web-Server"
    state: present
    include_sub_features: yes
    include_management_tools: yes
    restart: yes
    
# TOWER NOTE: chocolatey state only takes present or absent
# Install chocolatey to get git
- name: Install chocolatey
  win_chocolatey:
    name: chocolatey
    state: present
    
# Install git for repo cloning later
- name: Install git
  win_chocolatey:
    name: git
    state: present

# TOWER NOTE: win_path not supported? it throws an error as a YAML error because the task isn't recognized
# Ensure git is in the system path
#- name: Add git to the PATH
#  win_path:
#    elements: '%SystemRoot%\Program Files\Git\bin'
#    state: present

# Ansible seems to struggle with setting environment variables via modules
# Hopefully a direct command will make the difference
#- name: Add git to the PATH
#  win_environment:
#    name: PATH
#    level: machine
#    value: 

# Get archiving tools to handle more archive types
- name: Get PSCX msi
  win_get_url:
    url: '{{ pcsx_url }}'
    dest: '{{ pcsx_path }}'
- name: Install PCSX
  win_msi:
    path: '{{ pcsx_path }}'
    wait: True
- name: Clean up PCSX msi
  win_file:
    path: '{{ pcsx_path }}'
    state: absent
